# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build_base_image
  - lint
  - unit-test
  - vsphere_extension_tests
  - functionality_tests-environment-deploy
  - functionality_tests
  - functionality_tests-environment-delete
  - deploy

variables:
  CI_BASE_IMAGE: $PROD_URL/ray_taiga_cicd/oss-ci-base_test
  CI_TEST_IMAGE: $PROD_URL/ray_taiga_cicd/oss-ci_test
  # DOCKER_DRIVER: overlay
  DEFAULT_BRANCH: remotes/origin/oss-master
  DEFAULT_WHL: $RAY_WHL
  CI_PIPELINE_ID: $CI_PIPELINE_ID

  DEV_CPU_VSPHERE_SERVER: $DEV_CPU_VSPHERE_SERVER
  DEV_CPU_VSPHERE_USER: $DEV_CPU_VSPHERE_USER
  DEV_CPU_VSPHERE_PASSWORD: $DEV_CPU_VSPHERE_PASSWORD
  CPU_RAY_IMAGE: harbor-repo.vmware.com/dockerhub-proxy-cache/rayproject/ray:nightly

  GPU_feature_pattern: '/^GPU.*/'
  DEV_GPU_VSPHERE_SERVER: $DEV_GPU_VSPHERE_SERVER
  DEV_GPU_VSPHERE_USER: $DEV_GPU_VSPHERE_USER
  DEV_GPU_VSPHERE_PASSWORD: $DEV_GPU_VSPHERE_PASSWORD
  GPU_RAY_IMAGE: harbor-repo.vmware.com/dockerhub-proxy-cache/rayproject/ray:nightly-gpu


default:
  tags:
    - docker

# $CI_TEST_IMAGE is the basis of lint and unit test and needs to be updated in time. 
# Since each build is time-consuming, it is only updated when it is a dev branch.
ci_env_docker_build:
  stage: build_base_image
  image: docker:latest
  script: 
    - docker login -u "$PROD_API_USER" -p "$PROD_API_KEY" "$PROD_URL"
    - docker pull $CI_BASE_IMAGE || true
    - docker pull $CI_TEST_IMAGE || true
    - docker build -t $CI_BASE_IMAGE --cache-from $CI_BASE_IMAGE -f ./ci/docker/base.test.Dockerfile .
    - sed -i '18d' ./ci/docker/test.Dockerfile
    - docker build --build-arg DOCKER_IMAGE_BASE_TEST=$CI_BASE_IMAGE -t $CI_TEST_IMAGE --cache-from $CI_TEST_IMAGE -f ./ci/docker/test.Dockerfile .
    - docker push $CI_BASE_IMAGE
    - docker push $CI_TEST_IMAGE
    - docker system prune -f
  only:
    - dev

# Convert from .buildkite/lint.rayci.yml "clang format"
lint_clang-format:
  stage: lint
  image: 
    name: "$CI_TEST_IMAGE"
  script: 
    - | 
      bash --login -i -c "
        pip install -c python/requirements_compiled.txt clang-format
        ./ci/lint/check-git-clang-format-output.sh 
      "
  allow_failure: true
  needs: []
  only:
    - merge_requests

# Convert from .buildkite/lint.rayci.yml "clang format"
lint_code-format:
  stage: lint
  image: 
    name: "$CI_TEST_IMAGE"
  script:
    - | 
      bash --login -i -c "
        pip install -c python/requirements_compiled.txt -r python/requirements/lint-requirements.txt
        FORMAT_SH_PRINT_DIFF=1 ./ci/lint/format.sh --all-scripts
      "
  allow_failure: false
  needs: []
  only:
    - merge_requests

# Convert from .buildkite/lint.rayci.yml "untested code snippet"
lint_untested-code-snippet:
  stage: lint
  image: 
    name: "$CI_TEST_IMAGE"
  script: 
    - | 
      bash --login -i -c "
        pip install -c python/requirements_compiled.txt semgrep
        semgrep ci --config semgrep.yml
      "
  allow_failure: true
  needs: []
  only:
    - merge_requests

# Convert from .buildkite/lint.rayci.yml "banned words"
lint_banned-words:
  stage: lint
  image: 
    name: "$CI_TEST_IMAGE"
  script: 
    - |
      bash --login -i -c "
        ./ci/lint/check-banned-words.sh 
      "
  allow_failure: false
  needs: []
  only:
    - merge_requests

# Convert from .buildkite/lint.rayci.yml "doc readme"
lint_doc-readme:
  stage: lint
  image: 
    name: "$CI_TEST_IMAGE"
  script: 
    - | 
      bash --login -i -c "
        pip install -c python/requirements_compiled.txt docutils
        cd python && python setup.py check --restructuredtext --strict --metadata
      "
  allow_failure: false
  needs: []
  only:
    - merge_requests

# # Convert from .buildkite/lint.rayci.yml "dashboard format"
# lint_dashboard-format:
#   stage: lint
#   image: 
#     name: "$CI_TEST_IMAGE"
#   script: 
#     - | 
#       bash --login -i -c "
#         ./ci/lint/check-dashboard-format.sh
#       "
#   allow_failure: true

# Convert from .buildkite/lint.rayci.yml "copyright format"
lint_copyright-format:
  stage: lint
  image: 
    name: "$CI_TEST_IMAGE"
  script: 
    - | 
      bash --login -i -c "
        ./ci/lint/copyright-format.sh -c
      "
  allow_failure: false
  needs: []
  only:
    - merge_requests

# Convert from .buildkite/lint.rayci.yml "bazel team"
lint_bazel-team:
  stage: lint
  image: 
    name: "$CI_TEST_IMAGE"
  script: 
    - | 
      bash --login -i -c "
        bazel query 'kind("cc_test", //...)' --output=xml | python ./ci/lint/check-bazel-team-owner.py
        bazel query 'kind("py_test", //...)' --output=xml | python ./ci/lint/check-bazel-team-owner.py
      "
  allow_failure: false
  needs: []
  only:
    - merge_requests

# Convert from .buildkite/lint.rayci.yml "bazel buildifier"
lint_bazel-buildifier:
  stage: lint
  image: 
    name: "$CI_TEST_IMAGE"
  script:
    - | 
      bash --login -i -c "
        ./ci/lint/check-bazel-buildifier.sh
      "
  allow_failure: true
  needs: []
  only:
    - merge_requests

# Convert from .buildkite/lint.rayci.yml "pytest format"
lint_pytest-format:
  stage: lint
  image: 
    name: "$CI_TEST_IMAGE"
  script: 
    - | 
      bash --login -i -c "
        pip install -c python/requirements_compiled.txt yq
        ./ci/lint/check-pytest-format.sh
      "
  allow_failure: true
  needs: []
  only:
    - merge_requests

# Convert from .buildkite/lint.rayci.yml "test coverage"
lint_test-coverage:
  stage: lint
  image: 
    name: "$CI_TEST_IMAGE"
  script: 
    - | 
      bash --login -i -c "
        python ci/pipeline/check-test-run.py
      "
  allow_failure: true
  needs: []
  only:
    - merge_requests

# Convert from .buildkite/lint.rayci.yml "api annotations"
# lint_api-annotations:
#   stage: lint
#   image: 
#     name: "$CI_TEST_IMAGE"
#   script: 
#     - | 
#       bash --login -i -c "
#         RAY_DISABLE_EXTRA_CPP=1 pip install -e python/[all]
#         ./ci/lint/check_api_annotations.py
#       "
#   allow_failure: true
#   only:
#     - merge_requests

# Convert from .buildkite/pipeline.test.yml "LinkCheck"
unit-test_LinkCheck:
  stage: unit-test
  image: 
    name: "$CI_TEST_IMAGE"
  script: 
    - | 
      bash --login -i -c "
        export LINT=1
        ./ci/env/install-dependencies.sh
        ./ci/ci.sh check_sphinx_links
      "
  allow_failure: true
  needs: []
  only:
    - merge_requests

# Convert from .buildkite/pipeline.test.yml "Tune soft imports test"
unit-test_Tune-soft-imports-test:
  stage: unit-test
  image: 
    name: "$CI_TEST_IMAGE"

  script: 
    - |
      bash --login -i -c "
        cleanup() { if [ "${BUILDKITE_PULL_REQUEST}" = "false" ]; then ./ci/build/upload_build_info.sh; fi }; trap cleanup EXIT
        # no TUNE_TESTING=1 on purpose
        ./ci/env/install-dependencies.sh
        ./ci/env/env_info.sh
        pip install -U $RAY_WHL
        python python/ray/setup-dev.py --skip rllib air tune train cloudpickle data internal tests experimental util workflow dag widgets cluster_utils.py _private dashboard scripts serve -y
        bazel test --config=ci $(./ci/run/bazel_export_options) --build_tests_only --test_tag_filters=soft_imports python/ray/tune/...
      "
  allow_failure: true
  needs: []
  only:
    - merge_requests

pytest-test_basic:
  stage: vsphere_extension_tests
  image:
    name: "$CI_TEST_IMAGE"
  before_script:
    - |
      bash --login -i -c "
        pip install -U $RAY_WHL
        python python/ray/setup-dev.py --skip rllib air tune train cloudpickle data internal tests experimental util workflow dag widgets cluster_utils.py _private dashboard scripts serve -y
      "
  script:
    - |
      bash --login -i -c "
        python -m pytest -v -s python/ray/tests/test_basic.py
      "
  allow_failure: true
  needs: []
  only:
    - merge_requests

pytest-test_vsphere:
  stage: vsphere_extension_tests
  image:
    name: "$CI_TEST_IMAGE"
  before_script:
    - |
      bash --login -i -c "
        pip install -U $RAY_WHL
        python python/ray/setup-dev.py --skip rllib air tune train cloudpickle data internal tests experimental util workflow dag widgets cluster_utils.py _private dashboard scripts serve -y
      "
  script:
    - |
      bash --login -i -c "
        python -m pytest -v -s python/ray/tests/vsphere
      "
  allow_failure: false
  needs: []
  only:
    - merge_requests

deploy-ray:
  stage: functionality_tests-environment-deploy
  image:
    name: "$CI_TEST_IMAGE"
  variables:
    VSPHERE_SERVER: "$DEV_CPU_VSPHERE_SERVER"
    VSPHERE_USER: "$DEV_CPU_VSPHERE_USER"
    VSPHERE_PASSWORD: "$DEV_CPU_VSPHERE_PASSWORD"
    SECURE_FILES_DOWNLOAD_PATH: "key/"
  before_script:
    - |
      curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
      cp key/ray-bootstrap-key.pem ~/ray-bootstrap-key.pem
      cp key/ray_bootstrap_public_key.key ~/ray_bootstrap_public_key.key
      chmod 0600 ~/ray-bootstrap-key.pem
      bash --login -i -c "
        pip install -U $RAY_WHL
        python python/ray/setup-dev.py --skip rllib air tune train cloudpickle data internal tests experimental util workflow dag widgets cluster_utils.py _private dashboard scripts serve -y
      "
      sed -i "s/cluster_name: default.*/cluster_name: default+${CI_PIPELINE_ID}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s#image: \"rayproject/ray-ml:latest\"#image: \"${CPU_RAY_IMAGE}\"#g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/name: frozen-vm.*/name: frozen-vm-1/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s&#    ssh_private_key: /path/to/your/key.pem&    ssh_private_key: ~/ray-bootstrap-key.pem&g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/pull_before_run: True/pull_before_run: False/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#       credentials:/        credentials:/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           user: vc_username/            user: ${VSPHERE_USER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           password: vc_password/            password: ${VSPHERE_PASSWORD}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           server: vc_address/            server: ${VSPHERE_SERVER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i 's&#    "/path1/on/remote/machine": "/path1/on/local/machine",&     "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler": "/builds/xlabs/x77-taiga/ray-oss/python/ray/autoscaler",&g' python/ray/autoscaler/vsphere/example-full.yaml
  script:
    - |
      cat python/ray/autoscaler/vsphere/example-full.yaml
      bash --login -i -c "
        ray up -y python/ray/autoscaler/vsphere/example-full.yaml --no-config-cache
      "
  allow_failure: false
  needs: []
  rules:
    - if: $CI_COMMIT_REF_NAME !~ $GPU_feature_pattern && $CI_PIPELINE_SOURCE == "merge_request_event"

functionality-ray-test:
  stage: functionality_tests
  image:
    name: "$CI_TEST_IMAGE"
  variables:
    VSPHERE_SERVER: "$DEV_CPU_VSPHERE_SERVER"
    VSPHERE_USER: "$DEV_CPU_VSPHERE_USER"
    VSPHERE_PASSWORD: "$DEV_CPU_VSPHERE_PASSWORD"
    SECURE_FILES_DOWNLOAD_PATH: "key/"
  before_script:
    - |
      curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
      cp key/ray-bootstrap-key.pem ~/ray-bootstrap-key.pem
      cp key/ray_bootstrap_public_key.key ~/ray_bootstrap_public_key.key
      chmod 0600 ~/ray-bootstrap-key.pem
      bash --login -i -c "
        pip install -U $RAY_WHL
        python python/ray/setup-dev.py --skip rllib air tune train cloudpickle data internal tests experimental util workflow dag widgets cluster_utils.py _private dashboard scripts serve -y
      "
      sed -i "s/cluster_name: default.*/cluster_name: default+${CI_PIPELINE_ID}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s#image: \"rayproject/ray-ml:latest\"#image: \"${CPU_RAY_IMAGE}\"#g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/name: frozen-vm.*/name: frozen-vm-1/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s&#    ssh_private_key: /path/to/your/key.pem&    ssh_private_key: ~/ray-bootstrap-key.pem&g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/pull_before_run: True/pull_before_run: False/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#       credentials:/        credentials:/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           user: vc_username/            user: ${VSPHERE_USER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           password: vc_password/            password: ${VSPHERE_PASSWORD}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           server: vc_address/            server: ${VSPHERE_SERVER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i 's&#    "/path1/on/remote/machine": "/path1/on/local/machine",&     "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler": "/builds/xlabs/x77-taiga/ray-oss/python/ray/autoscaler",&g' python/ray/autoscaler/vsphere/example-full.yaml
  script:
    - |
      cat python/ray/autoscaler/vsphere/example-full.yaml
      bash --login -i -c "
        ray exec python/ray/autoscaler/vsphere/example-full.yaml 'python -c \"import ray; ray.init()\"'
      "
  allow_failure: false
  needs: ["deploy-ray"]
  rules:
    - if: $CI_COMMIT_REF_NAME !~ $GPU_feature_pattern && $CI_PIPELINE_SOURCE == "merge_request_event"

delete-ray:
  stage: functionality_tests-environment-delete
  image:
    name: "$CI_TEST_IMAGE"
  variables:
    VSPHERE_SERVER: "$DEV_CPU_VSPHERE_SERVER"
    VSPHERE_USER: "$DEV_CPU_VSPHERE_USER"
    VSPHERE_PASSWORD: "$DEV_CPU_VSPHERE_PASSWORD"
    SECURE_FILES_DOWNLOAD_PATH: "key/"
  before_script:
    - |
      curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
      cp key/ray-bootstrap-key.pem ~/ray-bootstrap-key.pem
      cp key/ray_bootstrap_public_key.key ~/ray_bootstrap_public_key.key
      chmod 0600 ~/ray-bootstrap-key.pem
      bash --login -i -c "
        pip install -U $RAY_WHL
        python python/ray/setup-dev.py --skip rllib air tune train cloudpickle data internal tests experimental util workflow dag widgets cluster_utils.py _private dashboard scripts serve -y
      "
      sed -i "s/cluster_name: default.*/cluster_name: default+${CI_PIPELINE_ID}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s#image: \"rayproject/ray-ml:latest\"#image: \"${CPU_RAY_IMAGE}\"#g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/name: frozen-vm.*/name: frozen-vm-1/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s&#    ssh_private_key: /path/to/your/key.pem&    ssh_private_key: ~/ray-bootstrap-key.pem&g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/pull_before_run: True/pull_before_run: False/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#       credentials:/        credentials:/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           user: vc_username/            user: ${VSPHERE_USER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           password: vc_password/            password: ${VSPHERE_PASSWORD}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           server: vc_address/            server: ${VSPHERE_SERVER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i 's&#    "/path1/on/remote/machine": "/path1/on/local/machine",&     "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler": "/builds/xlabs/x77-taiga/ray-oss/python/ray/autoscaler",&g' python/ray/autoscaler/vsphere/example-full.yaml
  script:
    - |
      cat python/ray/autoscaler/vsphere/example-full.yaml
      bash --login -i -c "
        ray down -y python/ray/autoscaler/vsphere/example-full.yaml
      "
  allow_failure: true
  needs: ["functionality-ray-test"]
  when: always
  rules:
    - if: $CI_COMMIT_REF_NAME !~ $GPU_feature_pattern && $CI_PIPELINE_SOURCE == "merge_request_event"


# GPU test
deploy-GPU-ray:
  stage: functionality_tests-environment-deploy
  image:
    name: "$CI_TEST_IMAGE"
  variables:
    VSPHERE_SERVER: "$DEV_GPU_VSPHERE_SERVER"
    VSPHERE_USER: "$DEV_GPU_VSPHERE_USER"
    VSPHERE_PASSWORD: "$DEV_GPU_VSPHERE_PASSWORD"
    SECURE_FILES_DOWNLOAD_PATH: "key/"
  before_script:
    - |
      curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
      cp key/ray-bootstrap-key.pem ~/ray-bootstrap-key.pem
      cp key/ray_bootstrap_public_key.key ~/ray_bootstrap_public_key.key
      chmod 0600 ~/ray-bootstrap-key.pem
      bash --login -i -c "
        pip install -U $RAY_WHL
        python python/ray/setup-dev.py --skip rllib air tune train cloudpickle data internal tests experimental util workflow dag widgets cluster_utils.py _private dashboard scripts serve -y
      "
      sed -i "s/cluster_name: default.*/cluster_name: default+${CI_PIPELINE_ID}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s#image: \"rayproject/ray-ml:latest\"#image: \"${GPU_RAY_IMAGE}\"#g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/name: frozen-vm.*/name: frozen-vm-1/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s&#    ssh_private_key: /path/to/your/key.pem&    ssh_private_key: ~/ray-bootstrap-key.pem&g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/pull_before_run: True/pull_before_run: False/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#       credentials:/        credentials:/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           user: vc_username/            user: ${VSPHERE_USER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           password: vc_password/            password: ${VSPHERE_PASSWORD}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           server: vc_address/            server: ${VSPHERE_SERVER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i 's&#    "/path1/on/remote/machine": "/path1/on/local/machine",&     "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler": "/builds/xlabs/x77-taiga/ray-oss/python/ray/autoscaler",&g' python/ray/autoscaler/vsphere/example-full.yaml
  script:
    - |
      cat python/ray/autoscaler/vsphere/example-full.yaml
      bash --login -i -c "
        # ray up -y python/ray/autoscaler/vsphere/example-full.yaml --no-config-cache
        echo 'Mockup: GPU-Ray deploy Success'
      "
  allow_failure: false
  needs: []
  rules:
    - if: $CI_COMMIT_REF_NAME =~ $GPU_feature_pattern && $CI_PIPELINE_SOURCE == "merge_request_event"

functionality-GPU-ray-test:
  stage: functionality_tests
  image:
    name: "$CI_TEST_IMAGE"
  variables:
    VSPHERE_SERVER: "$DEV_GPU_VSPHERE_SERVER"
    VSPHERE_USER: "$DEV_GPU_VSPHERE_USER"
    VSPHERE_PASSWORD: "$DEV_GPU_VSPHERE_PASSWORD"
    SECURE_FILES_DOWNLOAD_PATH: "key/"
  before_script:
    - |
      curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
      cp key/ray-bootstrap-key.pem ~/ray-bootstrap-key.pem
      cp key/ray_bootstrap_public_key.key ~/ray_bootstrap_public_key.key
      chmod 0600 ~/ray-bootstrap-key.pem
      bash --login -i -c "
        pip install -U $RAY_WHL
        python python/ray/setup-dev.py --skip rllib air tune train cloudpickle data internal tests experimental util workflow dag widgets cluster_utils.py _private dashboard scripts serve -y
      "
      sed -i "s/cluster_name: default.*/cluster_name: default+${CI_PIPELINE_ID}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s#image: \"rayproject/ray-ml:latest\"#image: \"${GPU_RAY_IMAGE}\"#g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/name: frozen-vm.*/name: frozen-vm-1/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s&#    ssh_private_key: /path/to/your/key.pem&    ssh_private_key: ~/ray-bootstrap-key.pem&g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/pull_before_run: True/pull_before_run: False/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#       credentials:/        credentials:/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           user: vc_username/            user: ${VSPHERE_USER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           password: vc_password/            password: ${VSPHERE_PASSWORD}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           server: vc_address/            server: ${VSPHERE_SERVER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i 's&#    "/path1/on/remote/machine": "/path1/on/local/machine",&     "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler": "/builds/xlabs/x77-taiga/ray-oss/python/ray/autoscaler",&g' python/ray/autoscaler/vsphere/example-full.yaml
  script:
    - |
      cat python/ray/autoscaler/vsphere/example-full.yaml
      bash --login -i -c "
        # ray exec python/ray/autoscaler/vsphere/example-full.yaml 'python -c \"import ray; ray.init()\"'
        echo 'Mockup: GPU-Ray functionality tests Success'
      "
  allow_failure: false
  needs: ["deploy-GPU-ray"]
  rules:
    - if: $CI_COMMIT_REF_NAME =~ $GPU_feature_pattern && $CI_PIPELINE_SOURCE == "merge_request_event"

delete-GPU-ray:
  stage: functionality_tests-environment-delete
  image:
    name: "$CI_TEST_IMAGE"
  variables:
    VSPHERE_SERVER: "$DEV_GPU_VSPHERE_SERVER"
    VSPHERE_USER: "$DEV_GPU_VSPHERE_USER"
    VSPHERE_PASSWORD: "$DEV_GPU_VSPHERE_PASSWORD"
    SECURE_FILES_DOWNLOAD_PATH: "key/"
  before_script:
    - |
      curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
      cp key/ray-bootstrap-key.pem ~/ray-bootstrap-key.pem
      cp key/ray_bootstrap_public_key.key ~/ray_bootstrap_public_key.key
      chmod 0600 ~/ray-bootstrap-key.pem
      bash --login -i -c "
        pip install -U $RAY_WHL
        python python/ray/setup-dev.py --skip rllib air tune train cloudpickle data internal tests experimental util workflow dag widgets cluster_utils.py _private dashboard scripts serve -y
      "
      sed -i "s/cluster_name: default.*/cluster_name: default+${CI_PIPELINE_ID}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s#image: \"rayproject/ray-ml:latest\"#image: \"${GPU_RAY_IMAGE}\"#g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/name: frozen-vm.*/name: frozen-vm-1/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s&#    ssh_private_key: /path/to/your/key.pem&    ssh_private_key: ~/ray-bootstrap-key.pem&g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/pull_before_run: True/pull_before_run: False/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#       credentials:/        credentials:/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           user: vc_username/            user: ${VSPHERE_USER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           password: vc_password/            password: ${VSPHERE_PASSWORD}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           server: vc_address/            server: ${VSPHERE_SERVER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i 's&#    "/path1/on/remote/machine": "/path1/on/local/machine",&     "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler": "/builds/xlabs/x77-taiga/ray-oss/python/ray/autoscaler",&g' python/ray/autoscaler/vsphere/example-full.yaml
  script:
    - |
      cat python/ray/autoscaler/vsphere/example-full.yaml
      bash --login -i -c "
        # ray down -y python/ray/autoscaler/vsphere/example-full.yaml
        echo 'Mockup: GPU-Ray delete Success'
      "
  allow_failure: true
  needs: ["functionality-GPU-ray-test"]
  when: always
  rules:
    - if: $CI_COMMIT_REF_NAME =~ $GPU_feature_pattern && $CI_PIPELINE_SOURCE == "merge_request_event"


deploy-dev-ray:
  stage: deploy
  image:
    name: "$CI_TEST_IMAGE"
  variables:
    VSPHERE_SERVER: "$DEV_CPU_VSPHERE_SERVER"
    VSPHERE_USER: "$DEV_CPU_VSPHERE_USER"
    VSPHERE_PASSWORD: "$DEV_CPU_VSPHERE_PASSWORD"
    SECURE_FILES_DOWNLOAD_PATH: "key/"
  before_script:
    - |
      curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
      cp key/ray-bootstrap-key.pem ~/ray-bootstrap-key.pem
      cp key/ray_bootstrap_public_key.key ~/ray_bootstrap_public_key.key
      chmod 0600 ~/ray-bootstrap-key.pem
      bash --login -i -c "
        pip install -U $RAY_WHL
        python python/ray/setup-dev.py --skip rllib air tune train cloudpickle data internal tests experimental util workflow dag widgets cluster_utils.py _private dashboard scripts serve -y
      "
      sed -i "s/cluster_name: default.*/cluster_name: branch-dev/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s#image: \"rayproject/ray-ml:latest\"#image: \"${CPU_RAY_IMAGE}\"#g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/name: frozen-vm.*/name: frozen-vm-1/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s&#    ssh_private_key: /path/to/your/key.pem&    ssh_private_key: ~/ray-bootstrap-key.pem&g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/pull_before_run: True/pull_before_run: False/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#       credentials:/        credentials:/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           user: vc_username/            user: ${VSPHERE_USER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           password: vc_password/            password: ${VSPHERE_PASSWORD}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i "s/#           server: vc_address/            server: ${VSPHERE_SERVER}/g" python/ray/autoscaler/vsphere/example-full.yaml
      sed -i 's&#    "/path1/on/remote/machine": "/path1/on/local/machine",&     "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler": "/builds/xlabs/x77-taiga/ray-oss/python/ray/autoscaler",&g' python/ray/autoscaler/vsphere/example-full.yaml
  script:
    - |
      cat python/ray/autoscaler/vsphere/example-full.yaml
      bash --login -i -c "
        ray down -y python/ray/autoscaler/vsphere/example-full.yaml
        ray up -y python/ray/autoscaler/vsphere/example-full.yaml --no-config-cache
        ray exec python/ray/autoscaler/vsphere/example-full.yaml 'python -c \"import ray; ray.init()\"'
      "
  allow_failure: false
  needs: []
  environment:
    name: dev
    action: start
  only:
    - dev
