import json
import logging
import os
from typing import Any, Dict, List, Tuple

import requests

# Design:

# Each modification the autoscaler wants to make is posted to the API server desired
# state (e.g. if the autoscaler wants to scale up, it adds VM name  to the desired
# worker list it wants to scale, if it wants to scale down it removes the name from
# the list).

# VMRay CRD version
VMRAY_CRD_VER = os.getenv("VMRAY_CRD_VER", "v1alpha1")

# VirtualMachine CRD version
VM_CRD_VER = os.getenv("VM_CRD_VER", "v1alpha1")

logger = logging.getLogger(__name__)


def load_k8s_secrets() -> Tuple[Dict[str, str], str]:
    """
    Loads secrets needed to access K8s resources.

    Returns:
        headers: Headers with K8s access token
        verify: Path to certificate
    """
    with open("/var/run/secrets/kubernetes.io/serviceaccount/token") as secret:
        token = secret.read()

    headers = {
        "Authorization": "Bearer " + token,
    }
    verify = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

    return headers, verify


def url_from_resource(namespace: str, path: str) -> str:
    """Convert resource path to REST URL for Kubernetes API server.

    Args:
        namespace: The K8s namespace of the resource
        path: The part of the resource path that starts with the resource type.
            Supported resource types are "pods" and "rayclusters".
    """
    if path.startswith("virtualmachine"):
        api_group = "/api/v1/" + VM_CRD_VER
    elif path.startswith("vmrayclusters"):
        api_group = "/apis/vmray.broadcom.com/" + VMRAY_CRD_VER
    else:
        raise NotImplementedError("Tried to access unknown entity at {}".format(path))
    return (
        "https://kubernetes.default:443"
        + api_group
        + "/namespaces/"
        + namespace
        + "/"
        + path
    )


class ClusterOperatorClient:
    def __init__(self, provider_config: Dict[str, Any]):
        logger.info("Creating Cluster Operator Client.")
        self.namespace = provider_config["namespace"]
        self.cluster_name = provider_config["cluster_name"]

        self.headers, self.verify = load_k8s_secrets()
        self.desiredWorkers = []

    def list_vms(self, clusterName: str, namespace: str) -> Dict[str, Any]:
        """Queries K8s for VMs in the RayCluster. Converts that vm data into a
        map of vm name to Ray NodeData, as required by VmRayNodeProvider.
        Call cluster operator -> pass cluster name, namespace
        """
        pass

    def is_vm_power_on(self, nodeId: str) -> bool:
        """Check current worker list. If its state is PowerON then return
        true else false."""

        pass

    def set_node_tags(self, tags: Dict[str, str]) -> None:
        """
        Not required
        """
        pass

    def get_vm_external_ip(self, name: str) -> str:
        """Check current worker list and get the external ip."""
        pass

    def delete_vms(self, vm_name: str) -> None:
        """Remove name of the vm from the desired worker list and patch
        the VmRayCluster CR"""
        pass

    def create_nodes(
        self,
        node_config: Dict[str, Any],
        filters: dict[str, str],
        to_be_launched_node_count: int,
    ) -> list[str]:
        """Queries K8s for VMs in the RayCluster. Converts that VM data into a
        map of VM name to Ray NodeData.
        add to desired worker list
        """
        pass

    def submit_scale_request(self, scale_request: Any):
        """Converts the scale request generated by VmRayNodeProvider into
        a patch that modifies the RayCluster CR's desired workers list
        fields. Then submits the patch to the K8s API server.
        """
        # Transform the scale request into a patch payload.
        patch_payload = self._scale_request_to_patch_payload(
            scale_request, self._raycluster
        )

        # Submit the patch to K8s.
        logger.info(
            "Autoscaler is submitting the following patch to RayCluster "
            f"{self.cluster_name} in namespace {self.namespace}."
        )
        logger.info(patch_payload)
        self._submit_raycluster_patch(patch_payload)

    def safe_to_scale(self) -> bool:
        """Returns False iff non_terminated_nodes contains any VMs in the RayCluster's
        workersToDelete lists.

        Explanation:
        If there are any workersToDelete which are non-terminated,
        we should wait for the operator to do its job and delete those
        pods. Therefore, we back off the autoscaler update.

        If, on the other hand, all of the workersToDelete have already been cleaned up,
        then we patch away the workersToDelete lists and return True.
        In the future, we may consider having the operator clean up workersToDelete
        on it own:
        https://github.com/ray-project/kuberay/issues/733

        """

        # It's safe to proceed with the autoscaler update.
        return True

    def _scale_request_to_patch_payload(
        self, scale_request: Any, raycluster: Dict[str, Any]
    ) -> List[Dict[str, Any]]:
        """Converts autoscaler scale request into a
        RayCluster CR patch payload."""
        patch_payload = []
        return patch_payload

    def _submit_raycluster_patch(self, patch_payload: List[Dict[str, Any]]):
        """Submits a patch to modify a RayCluster CR."""
        path = "vmrayclusters/{}".format(self.cluster_name)
        self._patch(path, patch_payload)

    def _url(self, path: str) -> str:
        """Convert resource path to REST URL for Kubernetes API server."""
        if path.startswith("pods"):
            api_group = "/api/v1"
        elif path.startswith("rayclusters"):
            api_group = "/apis/ray.io/" + VMRAY_CRD_VER
        else:
            raise NotImplementedError(
                "Tried to access unknown entity at {}".format(path)
            )
        return (
            "https://kubernetes.default:443"
            + api_group
            + "/namespaces/"
            + self.namespace
            + "/"
            + path
        )

    def _get(self, path: str) -> Dict[str, Any]:
        """Wrapper for REST GET of resource with proper headers."""
        url = url_from_resource(namespace=self.namespace, path=path)
        result = requests.get(url, headers=self.headers, verify=self.verify)
        if not result.status_code == 200:
            result.raise_for_status()
        return result.json()

    def _patch(self, path: str, payload: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Wrapper for REST PATCH of resource with proper headers."""
        url = url_from_resource(namespace=self.namespace, path=path)
        result = requests.patch(
            url,
            json.dumps(payload),
            headers={**self.headers, "Content-type": "application/json-patch+json"},
            verify=self.verify,
        )
        if not result.status_code == 200:
            result.raise_for_status()
        return result.json()
